package org.sceext.android_hook.qq.log_msg


// public static final int EXTRA_STREAM_PTT_FLAG = 10001
// public static final int MIN_VERSION_CODE_SUPPORT_IMAGE_MD5_TRANS = 2
const val MSG_TYPE_0x7F                               :String = "MSG_TYPE_0x7F"  // -2006
const val MSG_TYPE_ACTIVATE_FRIENDS                   :String = "MSG_TYPE_ACTIVATE_FRIENDS"  // -5003
const val MSG_TYPE_ACTIVITY                           :String = "MSG_TYPE_ACTIVITY"  // -4002
const val MSG_TYPE_AI_SPECIAL_GUIDE                   :String = "MSG_TYPE_AI_SPECIAL_GUIDE"  // -1052
const val MSG_TYPE_APPROVAL_GRAY_TIPS                 :String = "MSG_TYPE_APPROVAL_GRAY_TIPS"  // -2041
const val MSG_TYPE_APPROVAL_MSG                       :String = "MSG_TYPE_APPROVAL_MSG"  // -2040
const val MSG_TYPE_ARK_APP                            :String = "MSG_TYPE_ARK_APP"  // -5008
const val MSG_TYPE_ARK_BABYQ_REPLY                    :String = "MSG_TYPE_ARK_BABYQ_REPLY"  // -5016
const val MSG_TYPE_AUTHORIZE_FAILED                   :String = "MSG_TYPE_AUTHORIZE_FAILED"  // -4005
const val MSG_TYPE_AUTOREPLY                          :String = "MSG_TYPE_AUTOREPLY"  // -10000
const val MSG_TYPE_BAT_PROCESS_FILE                   :String = "MSG_TYPE_BAT_PROCESS_FILE"  // -3013
const val MSG_TYPE_BIT_APP_MSG                        :String = "MSG_TYPE_BIT_APP_MSG"  // -5009
const val MSG_TYPE_BIZ_DATA                           :String = "MSG_TYPE_BIZ_DATA"  // -2023
const val MSG_TYPE_C2C_CHAT_FREQ_CALL_TIP             :String = "MSG_TYPE_C2C_CHAT_FREQ_CALL_TIP"  // -1014
const val MSG_TYPE_C2C_KEYWORD_CALL_TIP               :String = "MSG_TYPE_C2C_KEYWORD_CALL_TIP"  // -1015
const val MSG_TYPE_C2C_MIXED                          :String = "MSG_TYPE_C2C_MIXED"  // -30002
const val MSG_TYPE_COLOR_RING_TIPS                    :String = "MSG_TYPE_COLOR_RING_TIPS"  // -3012
const val MSG_TYPE_CONFIGURABLE_GRAY_TIPS             :String = "MSG_TYPE_CONFIGURABLE_GRAY_TIPS"  // 2024
const val MSG_TYPE_CONFIGURABLE_TAB_VISIBLE_GRAY_TIPS :String = "MSG_TYPE_CONFIGURABLE_TAB_VISIBLE_GRAY_TIPS"  // -2042
const val MSG_TYPE_DATE_FEED                          :String = "MSG_TYPE_DATE_FEED"  // -1042
const val MSG_TYPE_DEVICE_CLOSEGROUPCHAT              :String = "MSG_TYPE_DEVICE_CLOSEGROUPCHAT"  // -4506
const val MSG_TYPE_DEVICE_DISMISSBIND                 :String = "MSG_TYPE_DEVICE_DISMISSBIND"  // -4507
const val MSG_TYPE_DEVICE_FILE                        :String = "MSG_TYPE_DEVICE_FILE"  // -4500
const val MSG_TYPE_DEVICE_LITTLE_VIDEO                :String = "MSG_TYPE_DEVICE_LITTLE_VIDEO"  // -4509
const val MSG_TYPE_DEVICE_OPENGROUPCHAT               :String = "MSG_TYPE_DEVICE_OPENGROUPCHAT"  // -4505
const val MSG_TYPE_DEVICE_PTT                         :String = "MSG_TYPE_DEVICE_PTT"  // -4501
const val MSG_TYPE_DEVICE_SHORT_VIDEO                 :String = "MSG_TYPE_DEVICE_SHORT_VIDEO"  // -4503
const val MSG_TYPE_DEVICE_SINGLESTRUCT                :String = "MSG_TYPE_DEVICE_SINGLESTRUCT"  // -4502
const val MSG_TYPE_DEVICE_TEXT                        :String = "MSG_TYPE_DEVICE_TEXT"  // -4508
const val MSG_TYPE_DINGDONG_SCHEDULE_MSG              :String = "MSG_TYPE_DINGDONG_SCHEDULE_MSG"  // -5010
const val MSG_TYPE_DING_DONG_GRAY_TIPS                :String = "MSG_TYPE_DING_DONG_GRAY_TIPS"  // -2034
const val MSG_TYPE_DISCUSS_PUSH                       :String = "MSG_TYPE_DISCUSS_PUSH"  // -1004
const val MSG_TYPE_DISCUSS_UPGRADE_TO_GROUP_TIPS      :String = "MSG_TYPE_DISCUSS_UPGRADE_TO_GROUP_TIPS"  // -1050
const val MSG_TYPE_DISC_CREATE_CALL_TIP               :String = "MSG_TYPE_DISC_CREATE_CALL_TIP"  // -1016
const val MSG_TYPE_DISC_PTT_FREQ_CALL_TIP             :String = "MSG_TYPE_DISC_PTT_FREQ_CALL_TIP"  // -1017
const val MSG_TYPE_ENTER_TROOP                        :String = "MSG_TYPE_ENTER_TROOP"  // -4003
const val MSG_TYPE_FAILED_MSG                         :String = "MSG_TYPE_FAILED_MSG"  // -2013
const val MSG_TYPE_FILE_RECEIPT                       :String = "MSG_TYPE_FILE_RECEIPT"  // -3008
const val MSG_TYPE_FLASH_CHAT                         :String = "MSG_TYPE_FLASH_CHAT"  // -5013
const val MSG_TYPE_FOLD_MSG_GRAY_TIPS                 :String = "MSG_TYPE_FOLD_MSG_GRAY_TIPS"  // -5011
const val MSG_TYPE_FORWARD_IMAGE                      :String = "MSG_TYPE_FORWARD_IMAGE"  // -20000
const val MSG_TYPE_FRIEND_SYSTEM_STRUCT_MSG           :String = "MSG_TYPE_FRIEND_SYSTEM_STRUCT_MSG"  // -2050
const val MSG_TYPE_GAME_INVITE                        :String = "MSG_TYPE_GAME_INVITE"  // -3004
const val MSG_TYPE_GAME_PARTY_GRAY_TIPS               :String = "MSG_TYPE_GAME_PARTY_GRAY_TIPS"  // -2049
const val MSG_TYPE_GAME_SHARE                         :String = "MSG_TYPE_GAME_SHARE"  // -3005
const val MSG_TYPE_GRAY_TIPS                          :String = "MSG_TYPE_GRAY_TIPS"  // -5000
const val MSG_TYPE_GRAY_TIPS_TAB_VISIBLE              :String = "MSG_TYPE_GRAY_TIPS_TAB_VISIBLE"  // -5001
const val MSG_TYPE_GROUPDISC_FILE                     :String = "MSG_TYPE_GROUPDISC_FILE"  // -2014
const val MSG_TYPE_HIBOOM                             :String = "MSG_TYPE_HIBOOM"  // -5014
const val MSG_TYPE_HOMEWORK_PRAISE                    :String = "MSG_TYPE_HOMEWORK_PRAISE"  // -2043
const val MSG_TYPE_HONGBAO_KEYWORDS_TIPS              :String = "MSG_TYPE_HONGBAO_KEYWORDS_TIPS"  // -1045
const val MSG_TYPE_HOT_CHAT_TO_SEE_TIP                :String = "MSG_TYPE_HOT_CHAT_TO_SEE_TIP"  // 1018
const val MSG_TYPE_INCOMPATIBLE_GRAY_TIPS             :String = "MSG_TYPE_INCOMPATIBLE_GRAY_TIPS"  // -5002
const val MSG_TYPE_INTERACT_AND_FOLLOW                :String = "MSG_TYPE_INTERACT_AND_FOLLOW"  // -2055
const val MSG_TYPE_LIFEONLINEACCOUNT                  :String = "MSG_TYPE_LIFEONLINEACCOUNT"  // -5004
const val MSG_TYPE_LIGHTALK_MSG                       :String = "MSG_TYPE_LIGHTALK_MSG"  // -2026
const val MSG_TYPE_LOCAL_COMMON                       :String = "MSG_TYPE_LOCAL_COMMON"  // -4000
const val MSG_TYPE_LOCAL_URL                          :String = "MSG_TYPE_LOCAL_URL"  // -4001
const val MSG_TYPE_LONG_MIX                           :String = "MSG_TYPE_LONG_MIX"  // -1036
const val MSG_TYPE_LONG_TEXT                          :String = "MSG_TYPE_LONG_TEXT"  // -1037
const val MSG_TYPE_MEDIA_EMO                          :String = "MSG_TYPE_MEDIA_EMO"  // -2001
const val MSG_TYPE_MEDIA_FILE                         :String = "MSG_TYPE_MEDIA_FILE"  // -2005
const val MSG_TYPE_MEDIA_FUNNY_FACE                   :String = "MSG_TYPE_MEDIA_FUNNY_FACE"  // -2010
const val MSG_TYPE_MEDIA_MARKFACE                     :String = "MSG_TYPE_MEDIA_MARKFACE"  // -2007
const val MSG_TYPE_MEDIA_MULTI09                      :String = "MSG_TYPE_MEDIA_MULTI09"  // -2003
const val MSG_TYPE_MEDIA_MULTI513                     :String = "MSG_TYPE_MEDIA_MULTI513"  // -2004
const val MSG_TYPE_MEDIA_PIC                          :String = "MSG_TYPE_MEDIA_PIC"  // -2000
const val MSG_TYPE_MEDIA_PTT                          :String = "MSG_TYPE_MEDIA_PTT"  // -2002
const val MSG_TYPE_MEDIA_SECRETFILE                   :String = "MSG_TYPE_MEDIA_SECRETFILE"  // -2008
const val MSG_TYPE_MEDIA_SHORTVIDEO                   :String = "MSG_TYPE_MEDIA_SHORTVIDEO"  // -2022
const val MSG_TYPE_MEDIA_VIDEO                        :String = "MSG_TYPE_MEDIA_VIDEO"  // -2009
const val MSG_TYPE_MEETING_NOTIFY                     :String = "MSG_TYPE_MEETING_NOTIFY"  // -5006
const val MSG_TYPE_MIX                                :String = "MSG_TYPE_MIX"  // -1035
const val MSG_TYPE_MULTI_TEXT_VIDEO                   :String = "MSG_TYPE_MULTI_TEXT_VIDEO"  // -4008
const val MSG_TYPE_MULTI_VIDEO                        :String = "MSG_TYPE_MULTI_VIDEO"  // -2016
const val MSG_TYPE_MY_ENTER_TROOP                     :String = "MSG_TYPE_MY_ENTER_TROOP"  // -4004
const val MSG_TYPE_NEARBY_DATING_SAFETY_TIP           :String = "MSG_TYPE_NEARBY_DATING_SAFETY_TIP"  // -1028
const val MSG_TYPE_NEARBY_DATING_TIP                  :String = "MSG_TYPE_NEARBY_DATING_TIP"  // -1024
const val MSG_TYPE_NEARBY_FLOWER_TIP                  :String = "MSG_TYPE_NEARBY_FLOWER_TIP"  // -2037
const val MSG_TYPE_NEARBY_LIVE_TIP                    :String = "MSG_TYPE_NEARBY_LIVE_TIP"  // -2053
const val MSG_TYPE_NEARBY_MARKET                      :String = "MSG_TYPE_NEARBY_MARKET"  // -2027
const val MSG_TYPE_NEARBY_RECOMMENDER                 :String = "MSG_TYPE_NEARBY_RECOMMENDER"  // -4011
const val MSG_TYPE_NEW_FRIEND_TIPS                    :String = "MSG_TYPE_NEW_FRIEND_TIPS"  // -1013
const val MSG_TYPE_NEW_FRIEND_TIPS_GAME_ADDEE         :String = "MSG_TYPE_NEW_FRIEND_TIPS_GAME_ADDEE"  // -1019
const val MSG_TYPE_NEW_FRIEND_TIPS_GAME_ADDER         :String = "MSG_TYPE_NEW_FRIEND_TIPS_GAME_ADDER"  // -1018
const val MSG_TYPE_NULL                               :String = "MSG_TYPE_NULL"  // -999
const val MSG_TYPE_ONLINE_FILE_REQ                    :String = "MSG_TYPE_ONLINE_FILE_REQ"  // -3007
const val MSG_TYPE_OPERATE_TIPS                       :String = "MSG_TYPE_OPERATE_TIPS"  // -1041
const val MSG_TYPE_PA_PHONE_MSG_TIPS                  :String = "MSG_TYPE_PA_PHONE_MSG_TIPS"  // -1048
const val MSG_TYPE_PC_PUSH                            :String = "MSG_TYPE_PC_PUSH"  // -3001
const val MSG_TYPE_PIC_AND_TEXT_MIXED                 :String = "MSG_TYPE_PIC_AND_TEXT_MIXED"  // -3000
const val MSG_TYPE_PIC_QSECRETARY                     :String = "MSG_TYPE_PIC_QSECRETARY"  // -1032
const val MSG_TYPE_PL_NEWS                            :String = "MSG_TYPE_PL_NEWS"  // -2060
const val MSG_TYPE_POKE_MSG                           :String = "MSG_TYPE_POKE_MSG"  // -5012
const val MSG_TYPE_PSTN_CALL                          :String = "MSG_TYPE_PSTN_CALL"  // -2046
const val MSG_TYPE_PTT_QSECRETARY                     :String = "MSG_TYPE_PTT_QSECRETARY"  // -1031
const val MSG_TYPE_PUBLIC_ACCOUNT                     :String = "MSG_TYPE_PUBLIC_ACCOUNT"  // -3006
const val MSG_TYPE_QLINK_AP_CREATE_SUC_TIPS           :String = "MSG_TYPE_QLINK_AP_CREATE_SUC_TIPS"  // -3011
const val MSG_TYPE_QLINK_FILE_TIPS                    :String = "MSG_TYPE_QLINK_FILE_TIPS"  // -3009
const val MSG_TYPE_QLINK_SEND_FILE_TIPS               :String = "MSG_TYPE_QLINK_SEND_FILE_TIPS"  // -3010
const val MSG_TYPE_QQSTORY                            :String = "MSG_TYPE_QQSTORY"  // -2051
const val MSG_TYPE_QQSTORY_COMMENT                    :String = "MSG_TYPE_QQSTORY_COMMENT"  // -2052
const val MSG_TYPE_QQWALLET_MSG                       :String = "MSG_TYPE_QQWALLET_MSG"  // -2025
const val MSG_TYPE_QQWALLET_TIPS                      :String = "MSG_TYPE_QQWALLET_TIPS"  // -2029
const val MSG_TYPE_QZONE_NEWEST_FEED                  :String = "MSG_TYPE_QZONE_NEWEST_FEED"  // -2015
const val MSG_TYPE_RECOMMAND_TIPS                     :String = "MSG_TYPE_RECOMMAND_TIPS"  // -5007
const val MSG_TYPE_RED_PACKET_TIPS                    :String = "MSG_TYPE_RED_PACKET_TIPS"  // -1044
const val MSG_TYPE_RENEWAL_TAIL_TIP                   :String = "MSG_TYPE_RENEWAL_TAIL_TIP"  // -4020
const val MSG_TYPE_REPLY_TEXT                         :String = "MSG_TYPE_REPLY_TEXT"  // -1049
const val MSG_TYPE_REVOKE_GRAY_TIPS                   :String = "MSG_TYPE_REVOKE_GRAY_TIPS"  // -2031
const val MSG_TYPE_SCRIBBLE_MSG                       :String = "MSG_TYPE_SCRIBBLE_MSG"  // -7001
const val MSG_TYPE_SENSITIVE_MSG_MASK_TIPS            :String = "MSG_TYPE_SENSITIVE_MSG_MASK_TIPS"  // -1046
const val MSG_TYPE_SHAKE_WINDOW                       :String = "MSG_TYPE_SHAKE_WINDOW"  // -2020
const val MSG_TYPE_SHARE_HOT_CHAT_GRAY_TIPS           :String = "MSG_TYPE_SHARE_HOT_CHAT_GRAY_TIPS"  // -2033
const val MSG_TYPE_SHARE_LBS_PUSH                     :String = "MSG_TYPE_SHARE_LBS_PUSH"  // -4010
const val MSG_TYPE_SHIELD_MSG                         :String = "MSG_TYPE_SHIELD_MSG"  // -2012
const val MSG_TYPE_SINGLE_WAY_FRIEND_MSG              :String = "MSG_TYPE_SINGLE_WAY_FRIEND_MSG"  // -2019
const val MSG_TYPE_SOUGOU_INPUT_TIPS                  :String = "MSG_TYPE_SOUGOU_INPUT_TIPS"  // -1043
const val MSG_TYPE_SPECIALCARE_TIPS                   :String = "MSG_TYPE_SPECIALCARE_TIPS"  // -5005
const val MSG_TYPE_SPLIT_LINE_GRAY_TIPS               :String = "MSG_TYPE_SPLIT_LINE_GRAY_TIPS"  // -4012
const val MSG_TYPE_STICKER_MSG                        :String = "MSG_TYPE_STICKER_MSG"  // -2058
const val MSG_TYPE_STRUCT_LONG_TEXT                   :String = "MSG_TYPE_STRUCT_LONG_TEXT"  // -1051
const val MSG_TYPE_STRUCT_MSG                         :String = "MSG_TYPE_STRUCT_MSG"  // -2011
const val MSG_TYPE_STRUCT_TROOP_NOTIFICATION          :String = "MSG_TYPE_STRUCT_TROOP_NOTIFICATION"  // -2021
const val MSG_TYPE_SYSTEM_STRUCT_MSG                  :String = "MSG_TYPE_SYSTEM_STRUCT_MSG"  // -2018
const val MSG_TYPE_TEXT                               :String = "MSG_TYPE_TEXT"  // -1000
const val MSG_TYPE_TEXT_FRIEND_FEED                   :String = "MSG_TYPE_TEXT_FRIEND_FEED"  // -1034
const val MSG_TYPE_TEXT_GROUPMAN_ACCEPT               :String = "MSG_TYPE_TEXT_GROUPMAN_ACCEPT"  // -1021
const val MSG_TYPE_TEXT_GROUPMAN_ADDREQUEST           :String = "MSG_TYPE_TEXT_GROUPMAN_ADDREQUEST"  // -1020
const val MSG_TYPE_TEXT_GROUPMAN_INVITE               :String = "MSG_TYPE_TEXT_GROUPMAN_INVITE"  // -1023
const val MSG_TYPE_TEXT_GROUPMAN_REFUSE               :String = "MSG_TYPE_TEXT_GROUPMAN_REFUSE"  // -1022
const val MSG_TYPE_TEXT_GROUP_CREATED                 :String = "MSG_TYPE_TEXT_GROUP_CREATED"  // -1047
const val MSG_TYPE_TEXT_QSECRETARY                    :String = "MSG_TYPE_TEXT_QSECRETARY"  // -1003
const val MSG_TYPE_TEXT_RECOMMEND_CIRCLE              :String = "MSG_TYPE_TEXT_RECOMMEND_CIRCLE"  // -1033
const val MSG_TYPE_TEXT_RECOMMEND_CONTACT             :String = "MSG_TYPE_TEXT_RECOMMEND_CONTACT"  // -1030
const val MSG_TYPE_TEXT_RECOMMEND_TROOP               :String = "MSG_TYPE_TEXT_RECOMMEND_TROOP"  // -1039
const val MSG_TYPE_TEXT_RECOMMEND_TROOP_BUSINESS      :String = "MSG_TYPE_TEXT_RECOMMEND_TROOP_BUSINESS"  // -1040
const val MSG_TYPE_TEXT_SAFE                          :String = "MSG_TYPE_TEXT_SAFE"  // -1002
const val MSG_TYPE_TEXT_SYSTEM_ACCEPT                 :String = "MSG_TYPE_TEXT_SYSTEM_ACCEPT"  // -1008
const val MSG_TYPE_TEXT_SYSTEM_ACCEPTANDADD           :String = "MSG_TYPE_TEXT_SYSTEM_ACCEPTANDADD"  // -1007
const val MSG_TYPE_TEXT_SYSTEM_ADDREQUEST             :String = "MSG_TYPE_TEXT_SYSTEM_ADDREQUEST"  // -1006
const val MSG_TYPE_TEXT_SYSTEM_ADDSUCCESS             :String = "MSG_TYPE_TEXT_SYSTEM_ADDSUCCESS"  // -1010
const val MSG_TYPE_TEXT_SYSTEM_OLD_VERSION_ADDREQUEST :String = "MSG_TYPE_TEXT_SYSTEM_OLD_VERSION_ADDREQUEST"  // -1011
const val MSG_TYPE_TEXT_SYSTEM_REFUSE                 :String = "MSG_TYPE_TEXT_SYSTEM_REFUSE"  // -1009
const val MSG_TYPE_TEXT_VIDEO                         :String = "MSG_TYPE_TEXT_VIDEO"  // -1001
const val MSG_TYPE_TIM_DOUFU_GUIDE                    :String = "MSG_TYPE_TIM_DOUFU_GUIDE"  // -3015
const val MSG_TYPE_TIM_GUIDE                          :String = "MSG_TYPE_TIM_GUIDE"  // -3014
const val MSG_TYPE_TROOP_DELIVER_GIFT                 :String = "MSG_TYPE_TROOP_DELIVER_GIFT"  // -2035
const val MSG_TYPE_TROOP_DELIVER_GIFT_OBJ             :String = "MSG_TYPE_TROOP_DELIVER_GIFT_OBJ"  // -2038
const val MSG_TYPE_TROOP_EFFECT_PIC                   :String = "MSG_TYPE_TROOP_EFFECT_PIC"  // -5015
const val MSG_TYPE_TROOP_FEE                          :String = "MSG_TYPE_TROOP_FEE"  // -2036
const val MSG_TYPE_TROOP_GAP_GRAY_TIPS                :String = "MSG_TYPE_TROOP_GAP_GRAY_TIPS"  // -2030
const val MSG_TYPE_TROOP_MIXED                        :String = "MSG_TYPE_TROOP_MIXED"  // -30003
const val MSG_TYPE_TROOP_NEWER_POBING                 :String = "MSG_TYPE_TROOP_NEWER_POBING"  // -2059
const val MSG_TYPE_TROOP_OBJ_MSG                      :String = "MSG_TYPE_TROOP_OBJ_MSG"  // -2017
const val MSG_TYPE_TROOP_REWARD                       :String = "MSG_TYPE_TROOP_REWARD"  // -2048
const val MSG_TYPE_TROOP_SIGN                         :String = "MSG_TYPE_TROOP_SIGN"  // -2054
const val MSG_TYPE_TROOP_STORY                        :String = "MSG_TYPE_TROOP_STORY"  // -2057
const val MSG_TYPE_TROOP_TIPS_ADD_MEMBER              :String = "MSG_TYPE_TROOP_TIPS_ADD_MEMBER"  // -1012
const val MSG_TYPE_TROOP_TOPIC                        :String = "MSG_TYPE_TROOP_TOPIC"  // -2044
const val MSG_TYPE_TROOP_TOPIC_OPEN_TIPS              :String = "MSG_TYPE_TROOP_TOPIC_OPEN_TIPS"  // -2032
const val MSG_TYPE_TROOP_UNREAD_TIPS                  :String = "MSG_TYPE_TROOP_UNREAD_TIPS"  // -4009
const val MSG_TYPE_TROOP_WANT_GIFT_MSG                :String = "MSG_TYPE_TROOP_WANT_GIFT_MSG"  // -2056
const val MSG_TYPE_UNCOMMONLY_USED_CONTACTS           :String = "MSG_TYPE_UNCOMMONLY_USED_CONTACTS"  // -1026
const val MSG_TYPE_UNCOMMONLY_USED_CONTACTS_CANCEL_SET:String = "MSG_TYPE_UNCOMMONLY_USED_CONTACTS_CANCEL_SET"  // -1027
const val MSG_TYPE_UNITE_GRAY_HISTORY_INVI            :String = "MSG_TYPE_UNITE_GRAY_HISTORY_INVI"  // -5021
const val MSG_TYPE_UNITE_GRAY_NORMAL                  :String = "MSG_TYPE_UNITE_GRAY_NORMAL"  // -5040
const val MSG_TYPE_UNITE_GRAY_TAB_INVI                :String = "MSG_TYPE_UNITE_GRAY_TAB_INVI"  // -5020
const val MSG_TYPE_UNITE_TAB_DB_INVI                  :String = "MSG_TYPE_UNITE_TAB_DB_INVI"  // -5022
const val MSG_TYPE_UNITE_TAB_HISTORI_INVI             :String = "MSG_TYPE_UNITE_TAB_HISTORI_INVI"  // -5023
const val MSG_TYPE_VAS_APOLLO                         :String = "MSG_TYPE_VAS_APOLLO"  // -2039
const val MSG_TYPE_VIP_AIO_SEND_TIPS                  :String = "MSG_TYPE_VIP_AIO_SEND_TIPS"  // -4022
const val MSG_TYPE_VIP_DONATE                         :String = "MSG_TYPE_VIP_DONATE"  // -2047
const val MSG_TYPE_VIP_KEYWORD                        :String = "MSG_TYPE_VIP_KEYWORD"  // -4021
const val MSG_TYPE_VIP_VIDEO                          :String = "MSG_TYPE_VIP_VIDEO"  // -2045
// public static final int MSG_VERSION_CODE = 3
// public static final int MSG_VERSION_CODE_FOR_PICPTT = 3
// public static final int SEND_FAIL_CODE_DEFAULT = 0
// public static final int SEND_FAIL_CODE_GOLDMSG_ERROR = -900


fun get_msg_type(x: Int): String = when(x) {
    -2006 -> MSG_TYPE_0x7F  // -2006
    -5003 -> MSG_TYPE_ACTIVATE_FRIENDS  // -5003
    -4002 -> MSG_TYPE_ACTIVITY  // -4002
    -1052 -> MSG_TYPE_AI_SPECIAL_GUIDE  // -1052
    -2041 -> MSG_TYPE_APPROVAL_GRAY_TIPS  // -2041
    -2040 -> MSG_TYPE_APPROVAL_MSG  // -2040
    -5008 -> MSG_TYPE_ARK_APP  // -5008
    -5016 -> MSG_TYPE_ARK_BABYQ_REPLY  // -5016
    -4005 -> MSG_TYPE_AUTHORIZE_FAILED  // -4005
   -10000 -> MSG_TYPE_AUTOREPLY  // -10000
    -3013 -> MSG_TYPE_BAT_PROCESS_FILE  // -3013
    -5009 -> MSG_TYPE_BIT_APP_MSG  // -5009
    -2023 -> MSG_TYPE_BIZ_DATA  // -2023
    -1014 -> MSG_TYPE_C2C_CHAT_FREQ_CALL_TIP  // -1014
    -1015 -> MSG_TYPE_C2C_KEYWORD_CALL_TIP  // -1015
   -30002 -> MSG_TYPE_C2C_MIXED  // -30002
    -3012 -> MSG_TYPE_COLOR_RING_TIPS  // -3012
     2024 -> MSG_TYPE_CONFIGURABLE_GRAY_TIPS  // 2024
    -2042 -> MSG_TYPE_CONFIGURABLE_TAB_VISIBLE_GRAY_TIPS  // -2042
    -1042 -> MSG_TYPE_DATE_FEED  // -1042
    -4506 -> MSG_TYPE_DEVICE_CLOSEGROUPCHAT  // -4506
    -4507 -> MSG_TYPE_DEVICE_DISMISSBIND  // -4507
    -4500 -> MSG_TYPE_DEVICE_FILE  // -4500
    -4509 -> MSG_TYPE_DEVICE_LITTLE_VIDEO  // -4509
    -4505 -> MSG_TYPE_DEVICE_OPENGROUPCHAT  // -4505
    -4501 -> MSG_TYPE_DEVICE_PTT  // -4501
    -4503 -> MSG_TYPE_DEVICE_SHORT_VIDEO  // -4503
    -4502 -> MSG_TYPE_DEVICE_SINGLESTRUCT  // -4502
    -4508 -> MSG_TYPE_DEVICE_TEXT  // -4508
    -5010 -> MSG_TYPE_DINGDONG_SCHEDULE_MSG  // -5010
    -2034 -> MSG_TYPE_DING_DONG_GRAY_TIPS  // -2034
    -1004 -> MSG_TYPE_DISCUSS_PUSH  // -1004
    -1050 -> MSG_TYPE_DISCUSS_UPGRADE_TO_GROUP_TIPS  // -1050
    -1016 -> MSG_TYPE_DISC_CREATE_CALL_TIP  // -1016
    -1017 -> MSG_TYPE_DISC_PTT_FREQ_CALL_TIP  // -1017
    -4003 -> MSG_TYPE_ENTER_TROOP  // -4003
    -2013 -> MSG_TYPE_FAILED_MSG  // -2013
    -3008 -> MSG_TYPE_FILE_RECEIPT  // -3008
    -5013 -> MSG_TYPE_FLASH_CHAT  // -5013
    -5011 -> MSG_TYPE_FOLD_MSG_GRAY_TIPS  // -5011
   -20000 -> MSG_TYPE_FORWARD_IMAGE  // -20000
    -2050 -> MSG_TYPE_FRIEND_SYSTEM_STRUCT_MSG  // -2050
    -3004 -> MSG_TYPE_GAME_INVITE  // -3004
    -2049 -> MSG_TYPE_GAME_PARTY_GRAY_TIPS  // -2049
    -3005 -> MSG_TYPE_GAME_SHARE  // -3005
    -5000 -> MSG_TYPE_GRAY_TIPS  // -5000
    -5001 -> MSG_TYPE_GRAY_TIPS_TAB_VISIBLE  // -5001
    -2014 -> MSG_TYPE_GROUPDISC_FILE  // -2014
    -5014 -> MSG_TYPE_HIBOOM  // -5014
    -2043 -> MSG_TYPE_HOMEWORK_PRAISE  // -2043
    -1045 -> MSG_TYPE_HONGBAO_KEYWORDS_TIPS  // -1045
     1018 -> MSG_TYPE_HOT_CHAT_TO_SEE_TIP  // 1018
    -5002 -> MSG_TYPE_INCOMPATIBLE_GRAY_TIPS  // -5002
    -2055 -> MSG_TYPE_INTERACT_AND_FOLLOW  // -2055
    -5004 -> MSG_TYPE_LIFEONLINEACCOUNT  // -5004
    -2026 -> MSG_TYPE_LIGHTALK_MSG  // -2026
    -4000 -> MSG_TYPE_LOCAL_COMMON  // -4000
    -4001 -> MSG_TYPE_LOCAL_URL  // -4001
    -1036 -> MSG_TYPE_LONG_MIX  // -1036
    -1037 -> MSG_TYPE_LONG_TEXT  // -1037
    -2001 -> MSG_TYPE_MEDIA_EMO  // -2001
    -2005 -> MSG_TYPE_MEDIA_FILE  // -2005
    -2010 -> MSG_TYPE_MEDIA_FUNNY_FACE  // -2010
    -2007 -> MSG_TYPE_MEDIA_MARKFACE  // -2007
    -2003 -> MSG_TYPE_MEDIA_MULTI09  // -2003
    -2004 -> MSG_TYPE_MEDIA_MULTI513  // -2004
    -2000 -> MSG_TYPE_MEDIA_PIC  // -2000
    -2002 -> MSG_TYPE_MEDIA_PTT  // -2002
    -2008 -> MSG_TYPE_MEDIA_SECRETFILE  // -2008
    -2022 -> MSG_TYPE_MEDIA_SHORTVIDEO  // -2022
    -2009 -> MSG_TYPE_MEDIA_VIDEO  // -2009
    -5006 -> MSG_TYPE_MEETING_NOTIFY  // -5006
    -1035 -> MSG_TYPE_MIX  // -1035
    -4008 -> MSG_TYPE_MULTI_TEXT_VIDEO  // -4008
    -2016 -> MSG_TYPE_MULTI_VIDEO  // -2016
    -4004 -> MSG_TYPE_MY_ENTER_TROOP  // -4004
    -1028 -> MSG_TYPE_NEARBY_DATING_SAFETY_TIP  // -1028
    -1024 -> MSG_TYPE_NEARBY_DATING_TIP  // -1024
    -2037 -> MSG_TYPE_NEARBY_FLOWER_TIP  // -2037
    -2053 -> MSG_TYPE_NEARBY_LIVE_TIP  // -2053
    -2027 -> MSG_TYPE_NEARBY_MARKET  // -2027
    -4011 -> MSG_TYPE_NEARBY_RECOMMENDER  // -4011
    -1013 -> MSG_TYPE_NEW_FRIEND_TIPS  // -1013
    -1019 -> MSG_TYPE_NEW_FRIEND_TIPS_GAME_ADDEE  // -1019
    -1018 -> MSG_TYPE_NEW_FRIEND_TIPS_GAME_ADDER  // -1018
     -999 -> MSG_TYPE_NULL  // -999
    -3007 -> MSG_TYPE_ONLINE_FILE_REQ  // -3007
    -1041 -> MSG_TYPE_OPERATE_TIPS  // -1041
    -1048 -> MSG_TYPE_PA_PHONE_MSG_TIPS  // -1048
    -3001 -> MSG_TYPE_PC_PUSH  // -3001
    -3000 -> MSG_TYPE_PIC_AND_TEXT_MIXED  // -3000
    -1032 -> MSG_TYPE_PIC_QSECRETARY  // -1032
    -2060 -> MSG_TYPE_PL_NEWS  // -2060
    -5012 -> MSG_TYPE_POKE_MSG  // -5012
    -2046 -> MSG_TYPE_PSTN_CALL  // -2046
    -1031 -> MSG_TYPE_PTT_QSECRETARY  // -1031
    -3006 -> MSG_TYPE_PUBLIC_ACCOUNT  // -3006
    -3011 -> MSG_TYPE_QLINK_AP_CREATE_SUC_TIPS  // -3011
    -3009 -> MSG_TYPE_QLINK_FILE_TIPS  // -3009
    -3010 -> MSG_TYPE_QLINK_SEND_FILE_TIPS  // -3010
    -2051 -> MSG_TYPE_QQSTORY  // -2051
    -2052 -> MSG_TYPE_QQSTORY_COMMENT  // -2052
    -2025 -> MSG_TYPE_QQWALLET_MSG  // -2025
    -2029 -> MSG_TYPE_QQWALLET_TIPS  // -2029
    -2015 -> MSG_TYPE_QZONE_NEWEST_FEED  // -2015
    -5007 -> MSG_TYPE_RECOMMAND_TIPS  // -5007
    -1044 -> MSG_TYPE_RED_PACKET_TIPS  // -1044
    -4020 -> MSG_TYPE_RENEWAL_TAIL_TIP  // -4020
    -1049 -> MSG_TYPE_REPLY_TEXT  // -1049
    -2031 -> MSG_TYPE_REVOKE_GRAY_TIPS  // -2031
    -7001 -> MSG_TYPE_SCRIBBLE_MSG  // -7001
    -1046 -> MSG_TYPE_SENSITIVE_MSG_MASK_TIPS  // -1046
    -2020 -> MSG_TYPE_SHAKE_WINDOW  // -2020
    -2033 -> MSG_TYPE_SHARE_HOT_CHAT_GRAY_TIPS  // -2033
    -4010 -> MSG_TYPE_SHARE_LBS_PUSH  // -4010
    -2012 -> MSG_TYPE_SHIELD_MSG  // -2012
    -2019 -> MSG_TYPE_SINGLE_WAY_FRIEND_MSG  // -2019
    -1043 -> MSG_TYPE_SOUGOU_INPUT_TIPS  // -1043
    -5005 -> MSG_TYPE_SPECIALCARE_TIPS  // -5005
    -4012 -> MSG_TYPE_SPLIT_LINE_GRAY_TIPS  // -4012
    -2058 -> MSG_TYPE_STICKER_MSG  // -2058
    -1051 -> MSG_TYPE_STRUCT_LONG_TEXT  // -1051
    -2011 -> MSG_TYPE_STRUCT_MSG  // -2011
    -2021 -> MSG_TYPE_STRUCT_TROOP_NOTIFICATION  // -2021
    -2018 -> MSG_TYPE_SYSTEM_STRUCT_MSG  // -2018
    -1000 -> MSG_TYPE_TEXT  // -1000
    -1034 -> MSG_TYPE_TEXT_FRIEND_FEED  // -1034
    -1021 -> MSG_TYPE_TEXT_GROUPMAN_ACCEPT  // -1021
    -1020 -> MSG_TYPE_TEXT_GROUPMAN_ADDREQUEST  // -1020
    -1023 -> MSG_TYPE_TEXT_GROUPMAN_INVITE  // -1023
    -1022 -> MSG_TYPE_TEXT_GROUPMAN_REFUSE  // -1022
    -1047 -> MSG_TYPE_TEXT_GROUP_CREATED  // -1047
    -1003 -> MSG_TYPE_TEXT_QSECRETARY  // -1003
    -1033 -> MSG_TYPE_TEXT_RECOMMEND_CIRCLE  // -1033
    -1030 -> MSG_TYPE_TEXT_RECOMMEND_CONTACT  // -1030
    -1039 -> MSG_TYPE_TEXT_RECOMMEND_TROOP  // -1039
    -1040 -> MSG_TYPE_TEXT_RECOMMEND_TROOP_BUSINESS  // -1040
    -1002 -> MSG_TYPE_TEXT_SAFE  // -1002
    -1008 -> MSG_TYPE_TEXT_SYSTEM_ACCEPT  // -1008
    -1007 -> MSG_TYPE_TEXT_SYSTEM_ACCEPTANDADD  // -1007
    -1006 -> MSG_TYPE_TEXT_SYSTEM_ADDREQUEST  // -1006
    -1010 -> MSG_TYPE_TEXT_SYSTEM_ADDSUCCESS  // -1010
    -1011 -> MSG_TYPE_TEXT_SYSTEM_OLD_VERSION_ADDREQUEST  // -1011
    -1009 -> MSG_TYPE_TEXT_SYSTEM_REFUSE  // -1009
    -1001 -> MSG_TYPE_TEXT_VIDEO  // -1001
    -3015 -> MSG_TYPE_TIM_DOUFU_GUIDE  // -3015
    -3014 -> MSG_TYPE_TIM_GUIDE  // -3014
    -2035 -> MSG_TYPE_TROOP_DELIVER_GIFT  // -2035
    -2038 -> MSG_TYPE_TROOP_DELIVER_GIFT_OBJ  // -2038
    -5015 -> MSG_TYPE_TROOP_EFFECT_PIC  // -5015
    -2036 -> MSG_TYPE_TROOP_FEE  // -2036
    -2030 -> MSG_TYPE_TROOP_GAP_GRAY_TIPS  // -2030
   -30003 -> MSG_TYPE_TROOP_MIXED  // -30003
    -2059 -> MSG_TYPE_TROOP_NEWER_POBING  // -2059
    -2017 -> MSG_TYPE_TROOP_OBJ_MSG  // -2017
    -2048 -> MSG_TYPE_TROOP_REWARD  // -2048
    -2054 -> MSG_TYPE_TROOP_SIGN  // -2054
    -2057 -> MSG_TYPE_TROOP_STORY  // -2057
    -1012 -> MSG_TYPE_TROOP_TIPS_ADD_MEMBER  // -1012
    -2044 -> MSG_TYPE_TROOP_TOPIC  // -2044
    -2032 -> MSG_TYPE_TROOP_TOPIC_OPEN_TIPS  // -2032
    -4009 -> MSG_TYPE_TROOP_UNREAD_TIPS  // -4009
    -2056 -> MSG_TYPE_TROOP_WANT_GIFT_MSG  // -2056
    -1026 -> MSG_TYPE_UNCOMMONLY_USED_CONTACTS  // -1026
    -1027 -> MSG_TYPE_UNCOMMONLY_USED_CONTACTS_CANCEL_SET  // -1027
    -5021 -> MSG_TYPE_UNITE_GRAY_HISTORY_INVI  // -5021
    -5040 -> MSG_TYPE_UNITE_GRAY_NORMAL  // -5040
    -5020 -> MSG_TYPE_UNITE_GRAY_TAB_INVI  // -5020
    -5022 -> MSG_TYPE_UNITE_TAB_DB_INVI  // -5022
    -5023 -> MSG_TYPE_UNITE_TAB_HISTORI_INVI  // -5023
    -2039 -> MSG_TYPE_VAS_APOLLO  // -2039
    -4022 -> MSG_TYPE_VIP_AIO_SEND_TIPS  // -4022
    -2047 -> MSG_TYPE_VIP_DONATE  // -2047
    -4021 -> MSG_TYPE_VIP_KEYWORD  // -4021
    -2045 -> MSG_TYPE_VIP_VIDEO  // -2045

    else -> "<<unknow>>"
}
// check code:
// function check() { var l = atom.workspace.getActiveTextEditor().getSelections()[0].getText().split('\n'); for (var i = 0; i < l.length; i += 1) { var t = l[i]; if (t.trim().length < 1) { continue; } var first = Number.parseInt(t.split('->')[0]); var second = Number.parseInt(t.split('//')[1]); if (first != second) { console.log(t); } } }


const val INT_MSG_TYPE_0x7F:Int = -2006
const val INT_MSG_TYPE_ACTIVATE_FRIENDS:Int = -5003
const val INT_MSG_TYPE_ACTIVITY:Int = -4002
const val INT_MSG_TYPE_AI_SPECIAL_GUIDE:Int = -1052
const val INT_MSG_TYPE_APPROVAL_GRAY_TIPS:Int = -2041
const val INT_MSG_TYPE_APPROVAL_MSG:Int = -2040
const val INT_MSG_TYPE_ARK_APP:Int = -5008
const val INT_MSG_TYPE_ARK_BABYQ_REPLY:Int = -5016
const val INT_MSG_TYPE_AUTHORIZE_FAILED:Int = -4005
const val INT_MSG_TYPE_AUTOREPLY:Int = -10000
const val INT_MSG_TYPE_BAT_PROCESS_FILE:Int = -3013
const val INT_MSG_TYPE_BIT_APP_MSG:Int = -5009
const val INT_MSG_TYPE_BIZ_DATA:Int = -2023
const val INT_MSG_TYPE_C2C_CHAT_FREQ_CALL_TIP:Int = -1014
const val INT_MSG_TYPE_C2C_KEYWORD_CALL_TIP:Int = -1015
const val INT_MSG_TYPE_C2C_MIXED:Int = -30002
const val INT_MSG_TYPE_COLOR_RING_TIPS:Int = -3012
const val INT_MSG_TYPE_CONFIGURABLE_GRAY_TIPS:Int = 2024
const val INT_MSG_TYPE_CONFIGURABLE_TAB_VISIBLE_GRAY_TIPS:Int = -2042
const val INT_MSG_TYPE_DATE_FEED:Int = -1042
const val INT_MSG_TYPE_DEVICE_CLOSEGROUPCHAT:Int = -4506
const val INT_MSG_TYPE_DEVICE_DISMISSBIND:Int = -4507
const val INT_MSG_TYPE_DEVICE_FILE:Int = -4500
const val INT_MSG_TYPE_DEVICE_LITTLE_VIDEO:Int = -4509
const val INT_MSG_TYPE_DEVICE_OPENGROUPCHAT:Int = -4505
const val INT_MSG_TYPE_DEVICE_PTT:Int = -4501
const val INT_MSG_TYPE_DEVICE_SHORT_VIDEO:Int = -4503
const val INT_MSG_TYPE_DEVICE_SINGLESTRUCT:Int = -4502
const val INT_MSG_TYPE_DEVICE_TEXT:Int = -4508
const val INT_MSG_TYPE_DINGDONG_SCHEDULE_MSG:Int = -5010
const val INT_MSG_TYPE_DING_DONG_GRAY_TIPS:Int = -2034
const val INT_MSG_TYPE_DISCUSS_PUSH:Int = -1004
const val INT_MSG_TYPE_DISCUSS_UPGRADE_TO_GROUP_TIPS:Int = -1050
const val INT_MSG_TYPE_DISC_CREATE_CALL_TIP:Int = -1016
const val INT_MSG_TYPE_DISC_PTT_FREQ_CALL_TIP:Int = -1017
const val INT_MSG_TYPE_ENTER_TROOP:Int = -4003
const val INT_MSG_TYPE_FAILED_MSG:Int = -2013
const val INT_MSG_TYPE_FILE_RECEIPT:Int = -3008
const val INT_MSG_TYPE_FLASH_CHAT:Int = -5013
const val INT_MSG_TYPE_FOLD_MSG_GRAY_TIPS:Int = -5011
const val INT_MSG_TYPE_FORWARD_IMAGE:Int = -20000
const val INT_MSG_TYPE_FRIEND_SYSTEM_STRUCT_MSG:Int = -2050
const val INT_MSG_TYPE_GAME_INVITE:Int = -3004
const val INT_MSG_TYPE_GAME_PARTY_GRAY_TIPS:Int = -2049
const val INT_MSG_TYPE_GAME_SHARE:Int = -3005
const val INT_MSG_TYPE_GRAY_TIPS:Int = -5000
const val INT_MSG_TYPE_GRAY_TIPS_TAB_VISIBLE:Int = -5001
const val INT_MSG_TYPE_GROUPDISC_FILE:Int = -2014
const val INT_MSG_TYPE_HIBOOM:Int = -5014
const val INT_MSG_TYPE_HOMEWORK_PRAISE:Int = -2043
const val INT_MSG_TYPE_HONGBAO_KEYWORDS_TIPS:Int = -1045
const val INT_MSG_TYPE_HOT_CHAT_TO_SEE_TIP:Int = 1018
const val INT_MSG_TYPE_INCOMPATIBLE_GRAY_TIPS:Int = -5002
const val INT_MSG_TYPE_INTERACT_AND_FOLLOW:Int = -2055
const val INT_MSG_TYPE_LIFEONLINEACCOUNT:Int = -5004
const val INT_MSG_TYPE_LIGHTALK_MSG:Int = -2026
const val INT_MSG_TYPE_LOCAL_COMMON:Int = -4000
const val INT_MSG_TYPE_LOCAL_URL:Int = -4001
const val INT_MSG_TYPE_LONG_MIX:Int = -1036
const val INT_MSG_TYPE_LONG_TEXT:Int = -1037
const val INT_MSG_TYPE_MEDIA_EMO:Int = -2001
const val INT_MSG_TYPE_MEDIA_FILE:Int = -2005
const val INT_MSG_TYPE_MEDIA_FUNNY_FACE:Int = -2010
const val INT_MSG_TYPE_MEDIA_MARKFACE:Int = -2007
const val INT_MSG_TYPE_MEDIA_MULTI09:Int = -2003
const val INT_MSG_TYPE_MEDIA_MULTI513:Int = -2004
const val INT_MSG_TYPE_MEDIA_PIC:Int = -2000
const val INT_MSG_TYPE_MEDIA_PTT:Int = -2002
const val INT_MSG_TYPE_MEDIA_SECRETFILE:Int = -2008
const val INT_MSG_TYPE_MEDIA_SHORTVIDEO:Int = -2022
const val INT_MSG_TYPE_MEDIA_VIDEO:Int = -2009
const val INT_MSG_TYPE_MEETING_NOTIFY:Int = -5006
const val INT_MSG_TYPE_MIX:Int = -1035
const val INT_MSG_TYPE_MULTI_TEXT_VIDEO:Int = -4008
const val INT_MSG_TYPE_MULTI_VIDEO:Int = -2016
const val INT_MSG_TYPE_MY_ENTER_TROOP:Int = -4004
const val INT_MSG_TYPE_NEARBY_DATING_SAFETY_TIP:Int = -1028
const val INT_MSG_TYPE_NEARBY_DATING_TIP:Int = -1024
const val INT_MSG_TYPE_NEARBY_FLOWER_TIP:Int = -2037
const val INT_MSG_TYPE_NEARBY_LIVE_TIP:Int = -2053
const val INT_MSG_TYPE_NEARBY_MARKET:Int = -2027
const val INT_MSG_TYPE_NEARBY_RECOMMENDER:Int = -4011
const val INT_MSG_TYPE_NEW_FRIEND_TIPS:Int = -1013
const val INT_MSG_TYPE_NEW_FRIEND_TIPS_GAME_ADDEE:Int = -1019
const val INT_MSG_TYPE_NEW_FRIEND_TIPS_GAME_ADDER:Int = -1018
const val INT_MSG_TYPE_NULL:Int = -999
const val INT_MSG_TYPE_ONLINE_FILE_REQ:Int = -3007
const val INT_MSG_TYPE_OPERATE_TIPS:Int = -1041
const val INT_MSG_TYPE_PA_PHONE_MSG_TIPS:Int = -1048
const val INT_MSG_TYPE_PC_PUSH:Int = -3001
const val INT_MSG_TYPE_PIC_AND_TEXT_MIXED:Int = -3000
const val INT_MSG_TYPE_PIC_QSECRETARY:Int = -1032
const val INT_MSG_TYPE_PL_NEWS:Int = -2060
const val INT_MSG_TYPE_POKE_MSG:Int = -5012
const val INT_MSG_TYPE_PSTN_CALL:Int = -2046
const val INT_MSG_TYPE_PTT_QSECRETARY:Int = -1031
const val INT_MSG_TYPE_PUBLIC_ACCOUNT:Int = -3006
const val INT_MSG_TYPE_QLINK_AP_CREATE_SUC_TIPS:Int = -3011
const val INT_MSG_TYPE_QLINK_FILE_TIPS:Int = -3009
const val INT_MSG_TYPE_QLINK_SEND_FILE_TIPS:Int = -3010
const val INT_MSG_TYPE_QQSTORY:Int = -2051
const val INT_MSG_TYPE_QQSTORY_COMMENT:Int = -2052
const val INT_MSG_TYPE_QQWALLET_MSG:Int = -2025
const val INT_MSG_TYPE_QQWALLET_TIPS:Int = -2029
const val INT_MSG_TYPE_QZONE_NEWEST_FEED:Int = -2015
const val INT_MSG_TYPE_RECOMMAND_TIPS:Int = -5007
const val INT_MSG_TYPE_RED_PACKET_TIPS:Int = -1044
const val INT_MSG_TYPE_RENEWAL_TAIL_TIP:Int = -4020
const val INT_MSG_TYPE_REPLY_TEXT:Int = -1049
const val INT_MSG_TYPE_REVOKE_GRAY_TIPS:Int = -2031
const val INT_MSG_TYPE_SCRIBBLE_MSG:Int = -7001
const val INT_MSG_TYPE_SENSITIVE_MSG_MASK_TIPS:Int = -1046
const val INT_MSG_TYPE_SHAKE_WINDOW:Int = -2020
const val INT_MSG_TYPE_SHARE_HOT_CHAT_GRAY_TIPS:Int = -2033
const val INT_MSG_TYPE_SHARE_LBS_PUSH:Int = -4010
const val INT_MSG_TYPE_SHIELD_MSG:Int = -2012
const val INT_MSG_TYPE_SINGLE_WAY_FRIEND_MSG:Int = -2019
const val INT_MSG_TYPE_SOUGOU_INPUT_TIPS:Int = -1043
const val INT_MSG_TYPE_SPECIALCARE_TIPS:Int = -5005
const val INT_MSG_TYPE_SPLIT_LINE_GRAY_TIPS:Int = -4012
const val INT_MSG_TYPE_STICKER_MSG:Int = -2058
const val INT_MSG_TYPE_STRUCT_LONG_TEXT:Int = -1051
const val INT_MSG_TYPE_STRUCT_MSG:Int = -2011
const val INT_MSG_TYPE_STRUCT_TROOP_NOTIFICATION:Int = -2021
const val INT_MSG_TYPE_SYSTEM_STRUCT_MSG:Int = -2018
const val INT_MSG_TYPE_TEXT:Int = -1000
const val INT_MSG_TYPE_TEXT_FRIEND_FEED:Int = -1034
const val INT_MSG_TYPE_TEXT_GROUPMAN_ACCEPT:Int = -1021
const val INT_MSG_TYPE_TEXT_GROUPMAN_ADDREQUEST:Int = -1020
const val INT_MSG_TYPE_TEXT_GROUPMAN_INVITE:Int = -1023
const val INT_MSG_TYPE_TEXT_GROUPMAN_REFUSE:Int = -1022
const val INT_MSG_TYPE_TEXT_GROUP_CREATED:Int = -1047
const val INT_MSG_TYPE_TEXT_QSECRETARY:Int = -1003
const val INT_MSG_TYPE_TEXT_RECOMMEND_CIRCLE:Int = -1033
const val INT_MSG_TYPE_TEXT_RECOMMEND_CONTACT:Int = -1030
const val INT_MSG_TYPE_TEXT_RECOMMEND_TROOP:Int = -1039
const val INT_MSG_TYPE_TEXT_RECOMMEND_TROOP_BUSINESS:Int = -1040
const val INT_MSG_TYPE_TEXT_SAFE:Int = -1002
const val INT_MSG_TYPE_TEXT_SYSTEM_ACCEPT:Int = -1008
const val INT_MSG_TYPE_TEXT_SYSTEM_ACCEPTANDADD:Int = -1007
const val INT_MSG_TYPE_TEXT_SYSTEM_ADDREQUEST:Int = -1006
const val INT_MSG_TYPE_TEXT_SYSTEM_ADDSUCCESS:Int = -1010
const val INT_MSG_TYPE_TEXT_SYSTEM_OLD_VERSION_ADDREQUEST:Int = -1011
const val INT_MSG_TYPE_TEXT_SYSTEM_REFUSE:Int = -1009
const val INT_MSG_TYPE_TEXT_VIDEO:Int = -1001
const val INT_MSG_TYPE_TIM_DOUFU_GUIDE:Int = -3015
const val INT_MSG_TYPE_TIM_GUIDE:Int = -3014
const val INT_MSG_TYPE_TROOP_DELIVER_GIFT:Int = -2035
const val INT_MSG_TYPE_TROOP_DELIVER_GIFT_OBJ:Int = -2038
const val INT_MSG_TYPE_TROOP_EFFECT_PIC:Int = -5015
const val INT_MSG_TYPE_TROOP_FEE:Int = -2036
const val INT_MSG_TYPE_TROOP_GAP_GRAY_TIPS:Int = -2030
const val INT_MSG_TYPE_TROOP_MIXED:Int = -30003
const val INT_MSG_TYPE_TROOP_NEWER_POBING:Int = -2059
const val INT_MSG_TYPE_TROOP_OBJ_MSG:Int = -2017
const val INT_MSG_TYPE_TROOP_REWARD:Int = -2048
const val INT_MSG_TYPE_TROOP_SIGN:Int = -2054
const val INT_MSG_TYPE_TROOP_STORY:Int = -2057
const val INT_MSG_TYPE_TROOP_TIPS_ADD_MEMBER:Int = -1012
const val INT_MSG_TYPE_TROOP_TOPIC:Int = -2044
const val INT_MSG_TYPE_TROOP_TOPIC_OPEN_TIPS:Int = -2032
const val INT_MSG_TYPE_TROOP_UNREAD_TIPS:Int = -4009
const val INT_MSG_TYPE_TROOP_WANT_GIFT_MSG:Int = -2056
const val INT_MSG_TYPE_UNCOMMONLY_USED_CONTACTS:Int = -1026
const val INT_MSG_TYPE_UNCOMMONLY_USED_CONTACTS_CANCEL_SET:Int = -1027
const val INT_MSG_TYPE_UNITE_GRAY_HISTORY_INVI:Int = -5021
const val INT_MSG_TYPE_UNITE_GRAY_NORMAL:Int = -5040
const val INT_MSG_TYPE_UNITE_GRAY_TAB_INVI:Int = -5020
const val INT_MSG_TYPE_UNITE_TAB_DB_INVI:Int = -5022
const val INT_MSG_TYPE_UNITE_TAB_HISTORI_INVI:Int = -5023
const val INT_MSG_TYPE_VAS_APOLLO:Int = -2039
const val INT_MSG_TYPE_VIP_AIO_SEND_TIPS:Int = -4022
const val INT_MSG_TYPE_VIP_DONATE:Int = -2047
const val INT_MSG_TYPE_VIP_KEYWORD:Int = -4021
const val INT_MSG_TYPE_VIP_VIDEO:Int = -2045
